### ISSUE TITLE
v7 API down

### ISSUE THREAD

**Issue by daviddigital** [towards/basic_yahoo_finance#3]
Thanks for building this gem.

As you are no doubt aware the current version API is broken (https://query1.finance.yahoo.com/v7/finance/quote?symbols=AAPL), and the fix is committed but not released (using v6 instead of v7 in api path).

**Comment by brigriffin** [comment]
Hi @daviddigital,

Yes, there have been some changes and using the `v6` instead of the `v7` API is just a workaround for now. I will nevertheless plan a new release of this gem probably still today.

**Comment by brigriffin** [comment]
@daviddigital the new version 0.4.0 of the gem has now been released.

**Comment by daviddigital** [comment]
Awesome work @brigriffin

**Comment by daviddigital** [comment]
Now v6 is down 😢  https://query1.finance.yahoo.com/v6/finance/quote?symbols=AAPL 

Looking into alternatives and I'll create a PR if I find one

**Comment by daviddigital** [comment]
Short of doing something like using this endpoint for the graph (very wasteful) https://query1.finance.yahoo.com/v8/finance/chart/AAPL I couldn't see anything having a google and inspecting the network tab on their site.

I am probably going to have to investigate other options like https://site.financialmodelingprep.com/developer/docs/#Ticker-Search which unfortunately may not be suitable for this gem but meets my use case of getting some data for a hobby project.

**Comment by daviddigital** [comment]
If I'm wrong and you do think this resource provider would be useful I could submit a PR. Users of this gem would need to provide an API key for the service still.

I have seen some others move to this service e.g. OpenBB

**Comment by daviddigital** [comment]
Something promising via yfinance: https://github.com/ranaroussi/yfinance/blob/d9bfd291131ca70121c0fd0b027512a268b2fc8b/yfinance/scrapers/quote.py#LL23C16-L23C73

e.g.
https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=price

**Comment by daviddigital** [comment]
I’ll submit a PR for the v10 option yfinance use for review shortly

**Comment by brigriffin** [comment]
It was really just a matter of time until they also take down the v6 version of their API unfortunately... If you have a moment a PR would be very welcome for their new v10 API.

**Comment by daviddigital** [comment]
Thanks for merging the the PR @brigriffin 

Checking out your commits, looks good, like defaulting to price, but I had one thought about this inefficient process of handling multiple tickers.

For the request https://github.com/towards/basic_yahoo_finance/blob/156a24137209e73b7e17483e7f5b0c9ce3abbdfa/lib/basic_yahoo_finance.rb#L23 

Do you know how `open-uri` is handling the requests in terms of whether its starting a new connection each time? Yahoo finance's api can handle persistent connections so we should be able to use sometihng like [this](https://ruby-doc.org/stdlib-2.5.0/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-How+to+use+Net-3A-3AHTTP) so that we open the connection -> perform each of the requests -> close the connection. 

Let me know your thoughts. Maybe something for the future

**Comment by daviddigital** [comment]
Relevant gem which is a wrapper on the above https://github.com/drbrain/net-http-persistent

**Comment by daviddigital** [comment]
Confirming that `open-uri` is opening up a new connection each time.

Let me know if you'd like me to put together a PR @brigriffin

**Comment by hostingnuggets** [comment]
Great idea regarding the persistent connections, it should make the querying of multiple symbols faster. I tested with around 15 symbols and the speed it not too bad. If you have time a PR would be good, no urgency though as for now it works nicely.

**Comment by daviddigital** [comment]
Cool, I'll have a look next weekend, do you mind if we release the current build now and I'll close this issue?

**Comment by daviddigital** [comment]
Actually I ended up implementing this, just sorting out the error handling, seems to be a lot faster, PR to come shortly.

**Comment by daviddigital** [comment]
#5

**Comment by brigriffin** [comment]
Have a look at my latest commit 6644308 it includes full code coverage and that would be the commit I will use for a new release of the gem if you are fine with that.

**Comment by daviddigital** [comment]
Looks great @brigriffin thanks for fixing that test, let’s ship it!

**Comment by daviddigital** [comment]
What’s the best way let people know that they will need to append [“fmt”] to their existing code to get the formatted value? It’s in the updated readme under usage, do you think that’s enough?

**Comment by brigriffin** [comment]
Thanks for your feedback and contribution. I think for now it's fine like that, if many people open an issue because of that, we can always add a big warning in the README. I just released version 0.5.0 of the gem which includes all the newest changes.
