### ISSUE TITLE
api down 

### ISSUE THREAD

**Issue by daviddigital** [towards/basic_yahoo_finance#7]
Same issues on yfinance who used the same api - they’ve moved to a previous version https://github.com/maffin-io/maffin-app/pull/49

If I can find some time on the weekend I’ll put in a MR. No guarantee the new one won’t fail soon too

**Comment by daviddigital** [comment]
Pull request: https://github.com/towards/basic_yahoo_finance/pull/9

**Comment by brigriffin** [comment]
Hi, thank you for reporting and your latest PR #9. I also tested it and it looks all good so I will merge in a few minutes and later today release a new version of the them. If this happens more often I will adapt the code to be able to specify another API version or even URL as parameter.

**Comment by daviddigital** [comment]
Great idea, thanks @brigriffin

**Comment by brigriffin** [comment]
Let's see how long this API version stays valid... In the mean time I have released version 0.5.1 of this gem at https://rubygems.org/gems/basic_yahoo_finance
